insert into artists values (DEFAULT, 'Damien Rice');
insert into artists values (DEFAULT, 'U2');
insert into artists values (DEFAULT, 'FINNEAS');
insert into artists values (DEFAULT, 'Weekend');
insert into artists values (DEFAULT, 'Doja Cat');
insert into artists values (DEFAULT, 'Coldplay');
insert into artists values (DEFAULT, 'Muse');
insert into artists values (DEFAULT, 'Kirkorov');
insert into genres  values (DEFAULT, 'Folk');
insert into genres values (DEFAULT, 'Pop');
insert into genres values (DEFAULT, 'Rock');
insert into genres values (DEFAULT, 'Hip-hop');
insert into genres values (DEFAULT, 'Kirkorov');
insert into albums values (DEFAULT, '9', '2006-11-03');
insert into albums values (DEFAULT, 'The Joshua Tree', '1987-03-09');
insert into albums values (DEFAULT, 'After hours', '2020-03-20');
insert into albums values (DEFAULT, 'Hot Pink', '2018-11-07');
insert into albums values (DEFAULT, 'Will of the People','2022-08-26');
insert into albums values (DEFAULT, 'Reimagined','2020-02-21');
insert into albums values (DEFAULT, 'For You', '2007-10-10');
insert into albums values (DEFAULT, 'Blood Harmony', '2019-10-04');
insert into tracks values (DEFAULT, '9 crimes', 223, 1);
insert into tracks values (DEFAULT, 'Elephant', 357, 1);
insert into tracks values (DEFAULT, 'With or without you', 296, 2);
insert into tracks values (DEFAULT, 'Exit', 293, 2);
insert into tracks values (DEFAULT, 'Blinding lights', 200, 3);
insert into tracks values (DEFAULT, 'Until I bleed out', 190, 3);
insert into tracks values (DEFAULT, 'Cyber Sex', 166, 4);
insert into tracks values (DEFAULT, 'Say So', 238, 4);
insert into tracks values (DEFAULT, 'Will of the People', 100, 5);
insert into tracks values (DEFAULT, 'Verona', 100, 5);
insert into tracks values (DEFAULT, 'Cry Cry Cry', 184, 6);
insert into tracks values (DEFAULT, 'BrokEn', 148, 6);
insert into tracks values (DEFAULT, 'I will give you this live', 246, 7);
insert into tracks values (DEFAULT, 'YA', 666, 7);
insert into tracks values (DEFAULT, 'Die Alone', 262, 8);
insert into tracks values (DEFAULT, 'Lost My Mind', 293, 8);
insert into mixtapes  values (DEFAULT, 'Relax', '2019-10-04');
insert into mixtapes  values (DEFAULT, 'Doom', '2021-03-04');
insert into mixtapes  values (DEFAULT, 'KirkorovIsOurGod', '2008-10-04');
insert into mixtapes  values (DEFAULT, 'USA', '2019-12-30');
insert into mixtapes  values (DEFAULT, 'Europe', '2019-05-04');
insert into mixtapes  values (DEFAULT, 'Good Morning', '2018-07-09');
insert into mixtapes  values (DEFAULT, 'Sport', '2021-11-04');
insert into mixtapes  values (DEFAULT, 'Breakfast', '2021-10-04');
insert into artistsalbums  values (1, 1);
insert into artistsalbums  values (2, 2);
insert into artistsalbums  values (3, 8);
insert into artistsalbums  values (4, 3);
insert into artistsalbums  values (5, 4);
insert into artistsalbums  values (6, 6);
insert into artistsalbums  values (7, 5);
insert into artistsalbums  values (8, 7);
insert into artistsgenres  values (1, 1);
insert into artistsgenres  values (1, 3);
insert into artistsgenres  values (2, 2);
insert into artistsgenres  values (2, 3);
insert into artistsgenres  values (3, 4);
insert into artistsgenres  values (3, 2);
insert into artistsgenres  values (4, 2);
insert into artistsgenres  values (4, 4);
insert into artistsgenres  values (5, 2);
insert into artistsgenres  values (5, 4);
insert into artistsgenres  values (6, 5);
insert into artistsgenres  values (7, 3);
insert into artistsgenres  values (8, 1);
insert into artistsgenres  values (8, 2);
insert into artistsgenres  values (8, 3);
insert into artistsgenres  values (8, 4);
insert into artistsgenres  values (8, 5);
insert into tracksmixtapes values (1, 1);
insert into tracksmixtapes values (2, 1);
insert into tracksmixtapes values (15, 1);
insert into tracksmixtapes values (9, 2);
insert into tracksmixtapes values (12, 2);
insert into tracksmixtapes values (14, 2);
insert into tracksmixtapes values (13, 3);
insert into tracksmixtapes values (4, 4);
insert into tracksmixtapes values (3, 4);
insert into tracksmixtapes values (6, 5);
insert into tracksmixtapes values (8, 5);
insert into tracksmixtapes values (7, 6);
insert into tracksmixtapes values (10, 6);
insert into tracksmixtapes values (11, 7);
insert into tracksmixtapes values (3, 8);





